### ISSUE TITLE
Pre Bundled js/css?

### ISSUE THREAD

**Issue by jilen** [Jas-SinghFSU/HyprPanel#155]
`dart-sass` & `esbuild` / `bun` is required now,  it would be better if we can have prebuilt assets.

**Comment by Jas-SinghFSU** [comment]
Not sure if this is feasible since dart-sass rebuilds anytime a UI setting is changed (it has to, in order to rebuild the scss variables).

Bun also rebuilds on Hyprpanel restart. Is there a concern with build times? Currently it's in the single digit milliseconds I believe (hardware dependent of course).

**Comment by jilen** [comment]
Not really an issue. It is a bit wired that dependency binary size is larger than ags itself.
I found `sassc`  / `esbuild` can also have things done, it is much smaller
