### ISSUE TITLE
No top bar on Ubuntu 24

### ISSUE THREAD

**Issue by Thomas-Philippot** [Jas-SinghFSU/HyprPanel#159]
I just installed ags and Hyprpanel on my desktop (Ubuntu 24 with hyprland) and while ags is running, there is no top bar displaying

The notifications and volume popup are working fine though

Might be a dependency issue, I didn't find a way to install them all on Ubuntu

**Comment by matavach** [comment]
Can you list what dependencies you weren't able to get installed? I'm pretty confident we can find the issue from that.

Does hyprland reserve space for an invisible top bar, or does the top bar not show at all?

**Comment by Thomas-Philippot** [comment]
- bluez-utils
- grimblast
- networkmanager
- hyprpicker

There is no spacing at all, if I launch waybar, the windows shrink to reserve space and it display just fine.

but ags just don't launch any bar

**Comment by matavach** [comment]
Bluez-utils should be included in the apt package `bluez`

Network manager is part of gnome and should be included in Ubuntu by default I think, if not you can get it with apt as  `network-manager`

[Hyprpicker](https://github.com/hyprwm/hyprpicker) and [grimblast](https://github.com/hyprwm/contrib) will both need to be compiled from source.

Both include instructions for manual installations.

Since we can't see any errors being logged, let's go ahead and get these packages installed first. I don't think hyprpicker or grimblast will be causing the issue, but I can see networkmanager and bluez causing an error

**Comment by Thomas-Philippot** [comment]
That what I though about `bluez-utils` 
I installed all the packages, built `hyprpicker` and `grimblast` from source but nothing seems to change.

**Comment by smathles** [comment]
What sort of messages are displayed in the terminal if you run ags from there?

**Comment by Thomas-Philippot** [comment]
`(com.github.Aylur.ags:250292): Gtk-WARNING **: 22:57:08.303: Theme parsing error: gtk.css:7793:16: 'border-spacing' is not a valid property name`

**Comment by Jas-SinghFSU** [comment]
@Thomas-Philippot Could you try to run:
```
ags --clear-cache
```
Then restart and see it fixes anything?

**Comment by Thomas-Philippot** [comment]
when I run the command i have this error message :
`(com.github.Aylur.ags:110373): GLib-GIO-CRITICAL **: 10:04:27.094: g_application_run: assertion '!application->priv->must_quit_now' failed`

**Comment by Thomas-Philippot** [comment]
It turns out everything was installed fine, only the bar was toggle off by default.

`ags -t bar-0` fixed the issue
