### ISSUE TITLE
Hide unoccupied workspaces

### ISSUE THREAD

**Issue by jgroboredo** [Jas-SinghFSU/HyprPanel#37]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an option where unoccupied workspaces do not appear in the workspace list.

**Describe the solution you'd like**
When a given workspace is not in use, it would be nice if we could make its number not appear in the workspace list.
However, I'm not sure if this would make sense in the case where the user is not using workspace numbers.

**Additional context**
Take the following example, where only workspaces 1 and 3 have windows:

![image](https://github.com/user-attachments/assets/d6b21d7f-c2b5-4214-a016-84c0a652a306)

I would like to have an option to temporarily hide workspaces 2 and 4, while they are empty or not focused.

**Comment by rishav12s** [comment]
Another closely related feature in addition to this will be display only that workspace which is not listed to show on the module kind of like waybar 
what im trying to say is that if i choose to show 5 workspaces then if i switch to the 6th then it should show only the 6th with the previous 5 that were already there 
could be a very useful feature for low resolutions and small screens

**Comment by mbollemeijer** [comment]
If this could be monitor specific it would mimic waybar functionality perfectly, like @rishav12s said.

**Comment by its-19818942118** [comment]
yep i really need that manually changing stuff is a pain. is it possible to also dd functionality for showing active workspaces only like waybar???

**Comment by Jas-SinghFSU** [comment]
@mbollemeijer @rishav12s My experience with Waybar was brief, could you please describe the behavior you're wanting a bit more?

**Comment by Jas-SinghFSU** [comment]
Closed ticket by accident.

**Comment by smathles** [comment]
IIRC waybar behaviour (at least on my old setup) had the functionality where if one workspace is open, only '1' is shown in waybar (or whatever, can be emoji, dot, number etc). If you scroll to the next workspace, a second option opens in waybar, and remains while you are on the workspace. Moving off of that workspace will close that entry in the waybar workspace widget, unless you have opened a window in that workspace. 
This also applies for any arbitrary workspace, such as if you then press super+7 to go to workspace 7, that workspace will be shown in the waybar widget (in this case, if numbers are used it would display `7` instead of `3`, as it's the workspace (index?) that's displayed, not the total number of workspaces there are.

**Comment by rishav12s** [comment]
in the configuration of the bar there is an option to set the number of workspaces to be displayed which is by default 10 
however some screens may be small so all 10 workspace icons may look ugly or result in overflow 
so if we choose to display 5 workspaces instead of 10 then only those 5 will be shown as persistent and if we move to workspace 6 or 7 or any number above 5 then only those workspaces other then the original 5 should be displayed 

For eg : 
Originally I chose to display 5 workspaces 
1 2 3 4 5
when i switch to 8th workspace then 
1 2 3 4 5 8
if i open something in 8th then the icon remains otherwise it closes when i switch to another like
1 2 3 4 5 8 10 
or like this when i close everything in last two and open another >5 number workspace 
1 2 3 4 5 7

this feature is requested as currently only workspace till the number set in configuration is shown 
if i choose to use workspace 10 then when setting no. of workspaces to 5 or 6 hyprland will switch to it but ags wont display the number or icon (hope it explains)

**Comment by Jas-SinghFSU** [comment]
Ah gotcha, thank you for that explanation, that makes sense. Seems very useful, I'll look into that when I get a chance.

**Comment by Jas-SinghFSU** [comment]
Ill try to work on this today.

**Comment by Jas-SinghFSU** [comment]
Added

**Comment by jgroboredo** [comment]
Haven't tested it yet!
Yesterday, after updating `hyprland`, it started crashing on my computer every time I access a window in a group (not related with HyprPanel though). 

I will test this as soon as possible!

Thanks a lot for your work x)

**Comment by smathles** [comment]
@jgroboredo no stress, it's already been merged after a few tests.
