### ISSUE TITLE
[Feature] Clear all notifications shortcut

### ISSUE THREAD

**Issue by chucklefart** [Jas-SinghFSU/HyprPanel#377]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A CLI command to clear all notifications.
My intention would be to bind it to right-clicking the notification icon, but could be bound to a keyboard shortcut, etc.

**Describe alternatives you've considered**
A clear-all button exists in the notification menu already, I am just looking for a shortcut to trigger this

**Additional context**
N/A

**Comment by rubiin** [comment]
![image](https://github.com/user-attachments/assets/faa143c3-52c6-436e-946a-ba43e80e1ff0)
https://aylur.github.io/ags-docs/config/cli/

Since ags lets you run arbitary code, you can create a custom ts file that lops over the notification similar to how the clear all button does things. And then call the file with how its shown on the screenshot .

**Comment by Jas-SinghFSU** [comment]
@chucklefart Implemented, feel free to use:
```
ags -r "clearAllNotifications()"
```
