### ISSUE TITLE
[Feature] Custom icon for tray

### ISSUE THREAD

**Issue by Wateir** [Jas-SinghFSU/HyprPanel#393]
**Is your feature request related to a problem? Please describe.**
Systray icon don't match my Hyprpanel theme

**Describe the solution you'd like**
Make possible to add custom icon for soft on systray

**Describe alternatives you've considered**
Change one by one the icon on the soft file, but not always possible and complexe for soft who is propritary

**Comment by Jas-SinghFSU** [comment]
I'm deeply disappointed to learn that the DBus object that these applications create for system tray icons don't provide application names. So there is no way to know what system tray item is spotify, discord, etc... All we get is an icon and a list of actions of the tray item.

Unfortunately I can't implement this due to these limitations since we have no way to associate an app name with a systray item.

**Comment by Wateir** [comment]
But, if you have the icon, you can use that no ? something like if this icons is display, don't display it, but display this other.

for exemple, if systray want to display the beautiful spotify icon verry green, i replace it be the same on white only

**Comment by Jas-SinghFSU** [comment]
The issue is that electron apps don't have an ID other than a generic `chrome_status_icon_1`. That is the ID of both Slack and Discord but there is no mention of Slack or Discord in the response object.

What I can do is allows this functionality but make it known that not all icons can be mapped since not all icons in the tray have a useful unique id.

**Comment by Jas-SinghFSU** [comment]
Implemented
