### ISSUE TITLE
Will this project be affected by AGS v2(Astal)

### ISSUE THREAD

**Issue by iMithrellas** [Jas-SinghFSU/HyprPanel#456]
Hi, as the title suggests, I would like to know if this project will be affected by this upcoming merge in AGS, and possibly how. 
https://github.com/Aylur/ags/pull/504

**Comment by Jas-SinghFSU** [comment]
Once AGS v2 releases this project will be transitioning to it.

**Comment by Aylur** [comment]
FYI Astal is a library so you don't have to rely on AGS anymore, you could already start the migration process.
I'll document this more thoroughly, once I come up with an api for nix, but basically you should distribute projects using Astal+TypeScript as a bundled script.
You can either use `ags bundle` and distribute the bundled script which can be executed like any other executable (it has some quirks in cases where you also want to distribute assets and other data, will document it too in the future), or use meson (ags is currently the recommended way, since I expect 99.9% usage for personal use which ags is meant for, but for distributed projects like this I'd recommend using meson)
One of the goals of Astal is to see more projects like this, where its not just "an ags config" but a program of its own. Documenting distributed projects is currently a low prio, so feel free to ask if you need help.

**Comment by Jas-SinghFSU** [comment]
@Aylur That makes sense, thank you for the clarification. I'll probably start the migration process soon; appreciate it Aylur.

**Comment by rubiin** [comment]
@Jas-SinghFSU I would love to help in the transition given we make a milestone with tasks. Then anyone interested can take a task and migrate the codebase to astal.

**Comment by rubiin** [comment]
@Aylur is there a performance gain of any sorts from the current implementation. I was mostly interested in this.

**Comment by Aylur** [comment]
Its negligible amount if there is any. We are still just calling into C code, spidermonkey (gjs) is very well optimized so you shouldn't be worrying about it. Only real difference between a gjs+gtk and a vala/c+gtk project is just some extra memory gjs allocates to do its thing, performance difference won't be noticeable.
The difference between DX on the other hand is **huge** writing jsx code vs vala/c is imo very much worth it.
However, If you decide to go for gtk4, vala+[blueprint](https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/) might be just as good as jsx and might be worth considering if you really care about ~30mb difference

**Comment by andradei** [comment]
It will be great to have this be bundled in the AUR.

**Comment by Jas-SinghFSU** [comment]
> @Jas-SinghFSU I would love to help in the transition given we make a milestone with tasks. Then anyone interested can take a task and migrate the codebase to astal. We can start out with a next branch.

I totally forgot missed this until this thread just got pinged to me due to a new message. Sorry about that.

I haven't had a chance to make milestones since between work and life I have only had brief pockets of time so I've just used those to migrate as much as I can. Hopefully in the future I get a chance to make it more collaborative and get some time to set up some milestones.
