### ISSUE TITLE
Option to style special/hidden/scratchpad workspace separately

### ISSUE THREAD

**Issue by andradei** [Jas-SinghFSU/HyprPanel#556]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Special workspace shows in the bar when it's instantiated, it would be great to have it styled differently from the normal ones.

![image](https://github.com/user-attachments/assets/1ef8a352-fb43-4ac4-9366-86bc0cc371c8)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by comradeprozac** [comment]
There is an option in the configuration menu in Bar>Workspaces called Ignored Workspaces, I used  this regex: `^-\d\d?$` and that hid the special workspaces.

Note that this will hide *all* workspaces that are negative, which is where hyprland, as far as I understand, puts the special workspaces.

Maybe this should be the default behavior, maybe the regex should look for the workspace *name* instead of the *id* and look for the *special* name by default.
